<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Superstrike Raster Ink">
  <Actions category="tool-shortcuts">
    <text>Tool Shortcuts</text>
    <Action name="KritaShape/KisToolSuperstrikeInk">
      <icon>superstrike_mouse</icon>
      <text>Superstrike Raster Ink Tool</text>
      <whatsThis>Draw pressure-sensitive raster strokes with Superstrike smoothing.</whatsThis>
      <toolTip>Superstrike Raster Ink Tool</toolTip>
      <iconText>Superstrike Raster Ink Tool</iconText>
      <shortcut>Shift+B</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip>Draw pressure-sensitive raster strokes with Superstrike smoothing.</statusTip>
    </Action>
  </Actions>
</ActionCollection>
