<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Mouse Pressure Brush">
  <Actions category="tool-shortcuts">
    <text>Tool Shortcuts</text>
    <Action name="KritaShape/KisToolMousePressure">
      <icon>mouse_pressure_mouse</icon>
      <text>Mouse Pressure Brush Tool</text>
      <whatsThis>Draw pressure-sensitive strokes with optional path smoothing.</whatsThis>
      <toolTip>Mouse Pressure Brush Tool (Shift+B)</toolTip>
      <iconText>Mouse Pressure Brush Tool</iconText>
      <shortcut>Shift+B</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip>Draw pressure-sensitive strokes with optional path smoothing.</statusTip>
    </Action>
  </Actions>
</ActionCollection>
